### ISSUE TITLE
Problem with preview

### ISSUE THREAD

**Issue by TheShadow29** [masasam/emacs-easy-jekyll#1]
Hi
When doing a preview for a post, it is trying to execute `jekyll serve`. It is exiting abnormally. But for my system I need to do `bundle exec jekyll serve`. How do I go about fixing this?

**Comment by masasam** [comment]
Hi @TheShadow29 .
Thank you for comment.

It has been fixed with the following commit so please use the latest code.
https://github.com/masasam/emacs-easy-jekyll/commit/71233c3043d1e4ccb0ee3c2ffcee4f7334ce8ee2

Once I develop a little more, I will register to melpa.

**Comment by TheShadow29** [comment]
@masasam 
I am actually using the latest commit but for some reason, it is giving me the error. The exact error is 
`Process jekyll-serve exited abnormally with code 10`.
Doing `bundle exec jekyll serve` in terminal works well. I am confused where the error is creeping in from.

**Comment by masasam** [comment]
@TheShadow29 .

Are you using exec-path-from-shell?
I came across the error that golang's bundle was working on.
So I erased golang's bundle

**Comment by TheShadow29** [comment]
No, I am not using exec-path-from-shell. Should I use that?

**Comment by masasam** [comment]
@TheShadow29 

You are Doing bundle exec jekyll serve in terminal works well.
I think another bundle is running in emacs.
With exec-path-from-shell the same bundle as terminal works.
