### ISSUE TITLE
_pages

### ISSUE THREAD

**Issue by grauschnabel** [masasam/emacs-easy-jekyll#10]
Hej,

I would like to have pages, like `about.md` `contact.md` and more under the `_pages` subdirectory. Can I maintain that with easy-jekyll? This subdir will also get different subdirs with differen language codes like `_pages/de` and son on.

The difference to `_posts` is that this files do not get at yyyy-mm-dd- at the beginning of the files.
`easy-jekyll-next-postdir` and so on do not recognise this subdir. Did I miss some config options here?

Thanks,
Martin

**Comment by masasam** [comment]
Hi @grauschnabel .
Thank you for comment.
I've fixed an issue that didn't work in the `_pages` directory in this [commit](https://github.com/masasam/emacs-easy-jekyll/commit/1af4a6cea3be06cd2c34ddfaae834725fedc22c2).
Try setting your init.el to `(setq easy-jekyll-additional-postdir "_pages")` and test.
It perhaps will take about 6 hours from now until this commit is reflected in melpa.

**Comment by masasam** [comment]
Hi @grauschnabel .
Thank you for comment.
I've fixed an issue with the `_pages` directory.
Try setting your init.el to `(setq easy-jekyll-additional-postdir "_pages")` and test.
It perhaps will take about 6 hours from now until this commit is reflected in melpa.
![Screenshot from 2021-12-10 00-33-19](https://user-images.githubusercontent.com/19677939/145426264-8bd9d350-dd7a-4eea-b51a-47a35c724d5f.png)

**Comment by grauschnabel** [comment]
I tried this inside the `easy-jekyll-bloglist` .  But there the jekyll site breaks with
```
easy-jekyll-next-postdir: Wrong type argument: stringp, ("_pages")
```
but the other jekyll pages are not affected.

**Comment by masasam** [comment]
Thank you for the report.
I'm working fine with the following settings.

```
(setq easy-jekyll-basedir "~/PPAP1/")
(setq easy-jekyll-additional-postdir "_pages")
(setq easy-jekyll-url "http://example.com")
(setq easy-jekyll-bloglist '(((easy-jekyll-basedir . "~/PPAP2/")
			      (easy-jekyll-additional-postdir . "_pages")
			      (easy-jekyll-url . "http://example2.com")
			      (easy-jekyll-sshdomain . "blogdomain")
			      (easy-jekyll-root . "/home/jekyll"))
			     ((easy-jekyll-basedir . "~/PPAP3/")
			      (easy-jekyll-additional-postdir . "_pages")
			      (easy-jekyll-url . "http://example3.com"))))
```

Please tell me in detail your settings etc. when it does not work well.

**Comment by grauschnabel** [comment]
Hi,

now I have it exactly like you, so i get rid of the error,  but it doesn't go to the `_pages` page when pressing `.` or `,`

I don't want to have my config here, so I'll send you a PM.

**Comment by masasam** [comment]
I've fixed a bug that did not work when there was no folder such as de or ja in `easy-jekyll-additional-postdir` at https://github.com/masasam/emacs-easy-jekyll/commit/7f19af310162464956f2bc4c38c6b7e95cb20321.
Maybe I think this will be working so please test it at PM.

**Comment by grauschnabel** [comment]
Hi,

this bugfix works for me. Thanks a lot!
