### ISSUE TITLE
Package not part of MELPA

### ISSUE THREAD

**Issue by laermannjan** [masasam/emacs-easy-jekyll#2]
It seems your package is currently not listed as part of MELPA.

https://melpa.org/#/?q=easy-jekyll

**Comment by masasam** [comment]
Hi @laermannjan .
Now I am doing pull request.
I think it will be incorporated into melpa in a few days.
Please wait a little.
https://github.com/melpa/melpa/pull/5032

**Comment by laermannjan** [comment]
Nice. Thanks for your quick response. ;)
