### ISSUE TITLE
multiple postdirs

### ISSUE THREAD

**Issue by grauschnabel** [masasam/emacs-easy-jekyll#4]
Hi there,

How can I configure a site for having multiple post dirs? For example having multiple languages in subfolders?

- Martin

**Comment by masasam** [comment]
Hi @grauschnabel .
Thank you for comment.
I've fixed to be able to move by creating folders such as en and ja under _post directory in https://github.com/masasam/emacs-easy-jekyll/commit/06ee289dd735a523617e10226a75dd902f1be0b9 commit.
You can move with the following command.

    M-x easy-jekyll-select-postdir
    M-x easy-jekyll-next-postdir
    M-x easy-jekyll-previous-postdir

**Comment by grauschnabel** [comment]
Thats really great and so fast!  Thanks for that! If I would need a lisp programmer, I would come to you. :)
//Martin
