### ISSUE TITLE
Accessibility: Navigating posts by line with Emacspeak

### ISSUE THREAD

**Issue by devinprater** [masasam/emacs-easy-jekyll#5]
I use [Emacspeak](http://github.com/tvraman/emacspeak) to operate Emacs, as I am a person who is blind. I've recently created a Jekyll blog on Github Pages, so I wanted to use the two together. Since Easy-Jekyll is the most updated package, I decided to go with that. I was able to set up my blog, but when doing ~Easy-jekyll~ from M-x, I hear nothing when pressing "j" or "k" to navigate the posts. I can have "emacspeak-speak-line" with C-e l, but that is a workaround.

So, I am wondering if this can be fixed, or advised to speak the post line, preferably the name of the post first? Thanks so much for this package, it helps a lot.

**Comment by masasam** [comment]
Hi @devinprater .
Thank you for comment.
I've supported emacspeak at https://github.com/masasam/emacs-easy-jekyll/commit/75f057caf54714b4e8a0934107f1ff8a05fc5349 .

You can use it by setting the following in .emacs or init.el.

    (setq easy-jekyll-emacspeak t)

It takes about 6 hours to be reflected in melpa, so please wait for a while.

**Comment by devinprater** [comment]
Thank you so much for this fix. :)
