### ISSUE TITLE
Problem setting serve-flags

### ISSUE THREAD

**Issue by NicolasIriarte** [masasam/emacs-easy-jekyll#7]
Hello everyone. Recently I was trying to add some flags to jekyll but I fail. Can anyone give me some examples of how to set `easy-jekyll-serve-flags` or `easy-jekyll-serve-value`?

On my init.el I added:
`(setq easy-jekyll-serve-flags "-d /home/user/dir/blog/_site -s /home/user/dir/blog")`
But it is not work as expected.

**Comment by masasam** [comment]
Hi @NicolasIriarte .
Thank you for comment.
I think it will work if you do the following.

    (setq easy-jekyll-serve-flags "-d")
    (setq easy-jekyll-serve-value "/home/user/dir/blog/_site")
    (setq easy-jekyll-serve-flags2 "-s")
    (setq easy-jekyll-serve-value2 "/home/user/dir/blog")

I've added easy-jekyll-serve-flags2 and easy-jekyll-serve-value2, so please update easy-jekyll before trying.
