### ISSUE TITLE
Locating easy-jekyll-basedir

### ISSUE THREAD

**Issue by bnsv** [masasam/emacs-easy-jekyll#8]
Hello. Can you do me a favor. I have a difficulty to set the variable of easy-jekyll-basedir. I set it to my blog local directory like these:
``M-x customize-variable RET easy-jekyll-basedir RET "/home/bensisva/myblog.github.io" RET``
I apply and saved it but it said Saved and set but mismatch. So where is the correct basedir actually?. Also when I do M-x easy-jekyll it return a message "'jekyll' is not installed" even I do have Jekyll and the server working properly.

Thank you.

**Comment by masasam** [comment]
HI @bnsv .
Thanks for comment.

Please write in .emacs.d/init.el as follows.
```
(setq easy-jekyll-basedir "/home/bensisva/myblog.github.io/")
(setq easy-jekyll-url "https://yourdomain")
```
Please install jekyll as follows
```
gem install jekyll bundler
jekyll new my-awesome-site
cd my-awesome-site
bundle install --path vendor/bundle
```
Please install [exec-path-from-shell]( https://github.com/purcell/exec-path-from-shell).
Please write in .emacs.d/init.el as follows.
```
(when (memq window-system '(mac ns x))
  (exec-path-from-shell-initialize))
```
I think this will work.

**Comment by bnsv** [comment]
Thank you very much @masasam. It seems the real problem is solved by exec-path-from-shell. Btw, Do you have any suggestion how to create an article using org-mode instead of markdown. Thanks for your good work.

**Comment by masasam** [comment]
I'm glad it was useful.
If you write in jekyll, I think org2jekyll or ox-jekyll-md or org-protocol-jekyll,
If you don't stick to jekyll, I recommend [ox-hugo](https://ox-hugo.scripter.co/) or [easy-hugo](https://github.com/masasam/emacs-easy-hugo).

**Comment by bnsv** [comment]
I will stick with Jekyll, I love Ruby. Thanks for your recommendation. Salute.
