### ISSUE TITLE
JEKYLL_ENV=production  ?

### ISSUE THREAD

**Issue by grauschnabel** [masasam/emacs-easy-jekyll#9]
Hi there,

thanks for that great and usefull package.

Now I have a usecase when using minimal-mistakes with google analytics, the sites have to be built with

`JEKYLL_ENV=production bundle exec jekyll build ...`

Otherwise the google analytics javascript is missing on the site.
How can I make this work?

Thanks!

**Comment by masasam** [comment]
Hi @grauschnabel .
Thank you for comment.
Since emacs adapts environment variables at startup,
I think you should write "JEKYLL_ENV=production" in your shell (~/.profile or ~/.bash_profile or ~/.zshenv or ~/.bashrc or ~/.zshrc).
Perhaps this problem can be solved by using [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell).

**Comment by grauschnabel** [comment]
Hi @masasam,
thanks for your fast response!

The thing is, that this is quite usfull.  Can a do something that `p` (preview) does not use that `JEKYLL_ENV=production`, but `P` (publish) does it?

On the other hand, I don't know why, but easy-jekyll uses another environment than xterm. When i do a `bundle install` from the xterm the preview does not work, but when I do it inside emacs `M-! bundle install ret` the preview works fine.

But for some reason, a `M-! export JEKYLL_ENV=production ret` does not make p or P to use the production environment.  I cannot figure that out right now. Any ideas?

**Comment by masasam** [comment]
Thank you for telling me in detail.
I've added a function to use "JEKYLL_ENV=production" at publish and using "JEKYLL_ENV=development" at preview in this [commit](https://github.com/masasam/emacs-easy-jekyll/commit/a680696a46d3d1aaa589ee443f816808f4e12b64).
Try setting your init.el to "(setq easy-jekyll-publish-production t)" and test.
It perhaps will take about 6 hours from now until this commit is reflected in melpa.

**Comment by grauschnabel** [comment]
Just tested it just nu after upgrade via melpa, and it seems to work just fine!  Thanks for that fast implementation of that feature request! That makes life a lot easier. :)
